<h1>Szczegóły Książki</h1>

<div class="container gap-3">
    <div class="p-2 row">
        <div class="col-2">Tytuł</div>
        <div class="col rounded border"><?= $ksiazka['tytul'] ?></div>
    </div>
    <div class="p-2 row">
        <div class="col-2">Autor</div>
        <div class="col rounded border"><?= $ksiazka['id_autora'] ?></div>
    </div>
    <div class="p-2 row">
        <div class="col-2">Cena</div>
        <div class="col rounded border"><?= $ksiazka['cena'] ?></div>
    </div>
    <div class="p-2 row">
        <div class="col-2">Liczba stron</div>
        <div class="col rounded border"><?= $ksiazka['liczba_stron'] ?></div>
    </div>
    <div class="p-2 row">
        <div class="col-2">Opis</div>
        <div class="col rounded border"><?= $ksiazka['opis'] ?></div>
    </div>
</div>